#!/usr/bin/env bash
if [ -z "$1" ]; then
  echo "Argument not provided"
else
    export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Argument not provided"
else
    export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "Argument not provided"
else
    export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Argument not provided"
else
    export ASSOC_ID="$4"
fi

if [ -z "$5" ]; then
  echo "Argument not provided"
else
    export RT_ID="$5"
fi
echo "Detaching IGW …"
aws ec2 detach-internet-gateway \
  --internet-gateway-id "$IGW_ID" \
  --vpc-id "$VPC_ID"

echo "Deleting IGW …"
aws ec2 delete-internet-gateway \
  --internet-gateway-id "$IGW_ID"

echo "Deleting subnet …"
aws ec2 delete-subnet \
  --subnet-id "$SUBNET_ID"

echo "Disassociating route tables ..."
aws ec2 disassociate-route-table --association-id $ASSOC_ID


echo "Deleting route table …"
#aws ec2 delete-route-table --route-table-id "$RT_ID"

#delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID
#print out delete command
echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID $ASSOC_ID $RT_ID
vpc-02386d51db4cfc12f igw-00df1c798143afacb subnet-0961a21773a62a63e rtb-021ef9bcd1a62532b"