#!/usr/bin/env bash

echo "== put-objects"
#Check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name provided. eg ./bucket my-bucket-name"
  exit 1
fi

if [ -z "$2" ]; then
  echo "There needs to be a file name provided. eg ./bucket my-bucket-name file-name"
  exit 1
fi
BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key $OBJECT_KEY