#!/usr/bin/env bash
echo "== sync"
set -e
#check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name provided. eg ./bucket my-bucket-name"

  exit 1
fi
#checj for filename prefix
if [ -z "$2" ]; then
  echo "There needs to be a filename provided. eg ./bucket my-bucket-name my-filename-prefix"

  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2
FOLDER_NAME="random_files"

# If the folder exists, delete it first
if [ -d "$FOLDER_NAME" ]; then
    echo "Removing existing '$FOLDER_NAME' folder to start fresh..."
    rm -rf "$FOLDER_NAME"
fi

# Create a new folder
mkdir "$FOLDER_NAME"
cd "$FOLDER_NAME"

# Create and upload files
for i in 1 2 3; do
    FILE_NAME="${FILENAME_PREFIX}_$i.txt"
    head -c 512 /dev/urandom | base64 > "$FILE_NAME"
    
    echo "Created $FILE_NAME:"
    ls -lh "$FILE_NAME"
    echo "Sample content:"
    head -n 3 "$FILE_NAME"
    echo "------------------------------------"

    echo "Uploading $FILE_NAME to S3..."
    aws s3 cp "$FILE_NAME" "s3://${BUCKET_NAME}/${FILE_NAME}"
    echo "------------------------------------"
done

cd ..
echo "Current directory structure:"
tree

echo "All random files have been created and uploaded to s3://${BUCKET_NAME}."

aws s3 sync $FOLDER_NAME s3://$BUCKET_NAME/files